/* $Header:   H:/VCS/FCIT/MACH_IBM.H_V   1.23   19 Apr 1991 23:40:04   FJM  $ */
  
/* --------------------------------------------------------------------
*  Version control log:
* $Log:   H:/VCS/FCIT/MACH_IBM.H_V  $
 * 
 *    Rev 1.23   19 Apr 1991 23:40:04   FJM
 * No change.
 * 
 *    Rev 1.22   19 Apr 1991 23:28:14   FJM
 * No change.
 * 
 *    Rev 1.21   10 Apr 1991  9:06:58   FJM
 * No change.
 * 
 *    Rev 1.20   04 Apr 1991 14:14:50   FJM
 * No change.
 * 
 *    Rev 1.19   13 Mar 1991 15:14:16   FJM
 * No change.
 * 
 *    Rev 1.18   13 Mar 1991 15:01:52   FJM
 * No change.
 * 
 *    Rev 1.17   10 Feb 1991 18:04:00   FJM
 * No change.
 * 
 *    Rev 1.16   10 Feb 1991 17:35:02   FJM
 * No change.
 * 
 *    Rev 1.15   05 Feb 1991 14:52:18   FJM
 * No change.
 * 
 *    Rev 1.14   05 Feb 1991 14:34:04   FJM
 * No change.
 * 
 *    Rev 1.13   19 Jan 1991 14:33:58   FJM
 * No change.
 * 
 *    Rev 1.12   19 Jan 1991 14:18:26   FJM
 * No change.
 * 
 *    Rev 1.11   18 Jan 1991 17:34:54   FJM
 * No change.
 * 
 *    Rev 1.10   18 Jan 1991 17:21:32   FJM
 * No change.
 * 
 *    Rev 1.9   18 Jan 1991 16:54:00   FJM
 * No change.
 * 
 *    Rev 1.8   13 Jan 1991  0:59:28   FJM
 * No change.
 * 
 *    Rev 1.7   13 Jan 1991  0:33:58   FJM
 * No change.
 * 
 *    Rev 1.6   11 Jan 1991 13:11:14   FJM
 * No change.
 * 
 *    Rev 1.5   11 Jan 1991 12:44:32   FJM
 * No change.
 * 
 *    Rev 1.4   06 Jan 1991 16:52:36   FJM
 * No change.
 * 
 *    Rev 1.3   06 Jan 1991 14:11:08   FJM
 * No change.
 * 
 *    Rev 1.2   06 Jan 1991 13:19:40   FJM
 * No change.
 * 
 *    Rev 1.1   06 Jan 1991 12:46:40   FJM
 * Porting, formating, fixes and misc changes.
 *
 *    Rev 1.0   27 Dec 1990 20:17:24   FJM
 * Changes for porting.
*
*   Rev 1.1   22 Dec 1990 13:50:46   FJM
*
*   Rev 1.0   22 Dec 1990  0:27:30   FJM
*Initial revision.
*
* -------------------------------------------------------------------- */
  
  
#define FAR     far
#define HUGE    huge
  
